### ISSUE TITLE
Lower min SDK version

### ISSUE THREAD

**Issue by mwarning** [mwarning/trigger#14]
To run on older android versions. Current stuck at some missing style error.

**Comment by clach04** [comment]
@mwarning what are the versions of Android currently supported? I'm wondering if issue #10 is Android version related

**Comment by mwarning** [comment]
Currently Android 7.1 (API version 25) ans up. But there is no reason not to lower that. The file picker library supports API version 14 and up.

Here is the error: https://stackoverflow.com/questions/54827458/lowering-sdk-api-level-style-not-found

**Comment by mwarning** [comment]
#10 might be related, I cannot say without an error message.

**Comment by clach04** [comment]
Thanks! Posted PR #15.

**Comment by mwarning** [comment]
Minimal SDK version should be Android 5.0 now (API level 21).

**Comment by clach04** [comment]
I opened https://gitlab.com/fdroid/fdroiddata/issues/1696 to get FDroid metadata updated.

**Comment by mwarning** [comment]
ok, thanks!
