### ISSUE TITLE
1.7.2 build/app?

### ISSUE THREAD

**Issue by clach04** [mwarning/trigger#25]
https://github.com/mwarning/trigger/releases/tag/v1.7.2 sounds awesome! Will a prebuilt APK be available for download?

**Comment by mwarning** [comment]
I think I should change the version to 1.8.0, as this is not merely a bugfix version.
There will be an apk package later this day.

**Comment by mwarning** [comment]
Done. I have renamed 1.7.2 to 1.8.0. Now there is also an apk.
