### ISSUE TITLE
Sample ssh command

### ISSUE THREAD

**Issue by clach04** [mwarning/trigger#26]
Any value in adding a sample ssh command? The docs are clear on what the output should look like, but a small example may be useful. Here is a longer than needed but hopefully easy to understand sample:

    #!/bin/sh
    # Lock demo, suitable for use with ssh mode of https://github.com/mwarning/trigger

    COMMAND=$1

    case ${COMMAND} in
        lock | close | shut)
            # issue lock command
            # assume it was successful and report locked
            echo LOCKED
            ;;

        open | unlock)
            # issue unlock command
            # assume it was successful and report locked
            echo UNLOCKED
            ;;

        status | *)
            # issue status command
            # assume it was successful and default/report locked
            echo LOCKED
            ;;

    esac

    # Trigger 1.7.1 will show correct image assuming the above is clean
    # debug or additional information can then be displayed below
    # it shows up in a Toast style message
    # Date/time is a useful addition
    #echo debug test
    date

**Comment by mwarning** [comment]
We could add this to the wiki, as this is a server side script.
But it might be useful add some help about the client side commands to the app itself.

**Comment by mwarning** [comment]
Or we can add a documentation folder. What do you think?

**Comment by clach04** [comment]
Either sounds good. I'm leaning towards a docs directory. I can do a PR.
