### ISSUE TITLE
Compatible lock

### ISSUE THREAD

**Issue by SofianeBoumedine** [mwarning/trigger#36]
Hi,

At office we are interest to use your app for control the door lock and especially by Wifi (HTTPS request).
But we want know which system are compatible with the app.

Thank's in advance.

**Comment by mwarning** [comment]
I have not looked at any off the shelf lock systems. The App just performs a HTTPS GET request. That is a pretty generic approach.

Our system is just a web server written in Python  that toggles a pin. It runs on a Raspberry PI.

**Comment by SofianeBoumedine** [comment]
Ok thank's for you response. So for examples, if I take this product : https://lockitron.com/
And I configure Open URL : with this https://api.lockitron.com/v2/documentation#locking_and_unlocking
It will work ?

**Comment by mwarning** [comment]
The "Bolt" product uses Bluetooth. I haven't tested Bluetooth with trigger, so I cannot recommend it. Also, the API uses PUT, not GET requests. Trigger does not support that yet.

**Comment by mwarning** [comment]
A setup I know uses the EVCA EMZY hooked up a Raspberry PI. Another one has a 3D printed gear on top of the key stuck in the key lock. the gear is connected to a step motor and custom electronics.

**Comment by SofianeBoumedine** [comment]
Ok thank's :)

**Comment by mwarning** [comment]
For what it is worth. Trigger now supports the Nuki Smartlock and allows parsing the return message using a regex.
