### ISSUE TITLE
MQTT credentials are ignored

### ISSUE THREAD

**Issue by JochenFriedrich** [mwarning/trigger#38]
The MQTT credentials currently aren't used at all.

**Comment by mwarning** [comment]
Hi,

do you mean specific credentials, or is it not working at all?
I remember to have tested it with a Mosquitto MQTT server at some point.
But in general the code lacks testing.
The code in question is here: https://github.com/mwarning/trigger/blob/master/app/src/main/java/com/example/trigger/mqtt/MqttRequestHandler.java

**Comment by JochenFriedrich** [comment]
I mean userid and password setup fields. It looks like they need to be passed using opts.setUserid() and opts.setPassword() before calling client.connect(opts).

**Comment by mwarning** [comment]
You are right. Those fields were not set.

I hope this fixes it: https://github.com/mwarning/trigger/commit/7d1f9208bdd4a1b0f549fc73f23af148827a2c81

Can you test it?

**Comment by JochenFriedrich** [comment]
Many thanks. Looks good.
