### ISSUE TITLE
ssh key registration hangs

### ISSUE THREAD

**Issue by flashfingaz** [mwarning/trigger#40]
we are using the ssh key registration feature (btw. it would be nice to get rid of the forced schema, so users only need to enter host:port and not nnn://host:port) and we have tested it with a broad range of phones - but on all of them we need to force a kill of the app to have the pubkey sent.

would be great if you could look into this!

**Comment by flashfingaz** [comment]
this is our setup:
machine that spwans an nc on port 12345 and waits for input
client uses zzz://hostname:12345 then fireing up the process

it looks like there would be nothing happening, but by the same second you kill the app, data is received by nc. as i said this is the case on all phones we tested this on (at the moment around 6-8 different phones)

**Comment by mwarning** [comment]
Thanks for the feedback. I will look into it. :-)

**Comment by mwarning** [comment]
ok, I think I have fixed the hang issue. The register url now also defaults to the host address (save a bit of typing).
Are you able to test if the current fix works for you?

Anyway, can you elaborate on where you have to use a schema? It worked without for the register url.
I remember that I had a bit of problem with schemas, but I thought that was fixed and is purely optional now.

**Comment by flashfingaz** [comment]
We tested it today and it works like a charme!
The thing with the schema might be outdated, the first version of trigger we used needed this somehow and it might be I just was too used entering with schema that I totally missed the point where you got rid of that :) as for today, it worked completely without schema.

many thanks for the quick fix!

**Comment by mwarning** [comment]
Nice, I remember that a dummy schema was needed early on. The one SDK method that would let you validate IP addresses need a (dummy) schema.

Anyway, I made a new release. It should arrive in f-droid later this week.
