### ISSUE TITLE
Trigger is freezing on start up because it is not allowed to access location

### ISSUE THREAD

**Issue by zem** [mwarning/trigger#41]
As the subject says, trigger is freezing on start up and tries to get the location in an endless loop which is not allowed on the phone as there is no reason to allow it at startup.

**Comment by mwarning** [comment]
As far as I know, Trigger  only accesses the local database (except for manual import/export). Can you tell me how to reproduce this problem? What setup do you use?

**Comment by mwarning** [comment]
hm, or do you mean Trigger does not freeze indefinitely, but is only frezed for a short time?

**Comment by mwarning** [comment]
Can you check if the problem occurs with Trigger version 2.2.1?

**Comment by mwarning** [comment]
I think I can drop android.permission.ACCESS_FINE_LOCATION, it is only needed for Bluetooth scans. I will test it next week.

**Comment by mwarning** [comment]
Should be fixed in 2.2.4. Let me know if the problem persists.
