### ISSUE TITLE
can it be compatible to yeelock?

### ISSUE THREAD

**Issue by BunnyBug** [mwarning/trigger#43]
I have tried to add my "Smart Drawer Cabinet Lock", it didn't work, then i scanned its QR-code, but no response.

**Comment by mwarning** [comment]
I have never heard of the yeelock before. The QR-Code that trigger support are only it's own and simple http links.

The protocol also seems to have no documentation. The lock would need to be reverse engineered. Which needs an actual lock, time and luck.

**Comment by mwarning** [comment]
closing this, this is unlikely to happen
