### ISSUE TITLE
no connect via ssh

### ISSUE THREAD

**Issue by lada04** [mwarning/trigger#44]
I'm trying to control an SR-201 IP Relay via ssh and python. 
When trying to connect via ssh to the server, the toast 
`Session.connect: java.oi.IOException: End of IO Stream Read`
appears. 
![Screenshot_20200609-123048](https://user-images.githubusercontent.com/66674914/84141148-ff91b200-aa52-11ea-9adb-7e2685e1f0a1.png)

No login happens and the server log says:
`sshd[171698]: ssh_dispatch_run_fatal: Connection from 192.168.0.52 port 49083: DH GEX group out of range [preauth]`
while the port is incremented at each time. I've checked the public key and any other settings from the shell of a linux box - it works well there. 
Using on XPeria X Compact with Android 8.0.0 (Sep 2018).

**Comment by lada04** [comment]
the ssh server is 
`OpenSSH_8.3p1, OpenSSL 1.1.1g  21 Apr 2020`
mainly with the default config.

**Comment by mwarning** [comment]
That is an odd error. I think the client (trigger uses http://www.jcraft.com/jsch/) needs some option to be set.
I will test it with my laptop when I have a moment.

**Comment by mwarning** [comment]
I was able to recreate a problem. A library update fixed it:

https://github.com/mwarning/trigger/releases/tag/v3.0.1

**Comment by lada04** [comment]
Great, this solved the issue for me.
