### ISSUE TITLE
Support for ssh-keys mit passphrase support

### ISSUE THREAD

**Issue by rdorsch** [mwarning/trigger#45]
Supporting ssh-keys with passphrase support would be very handy to implement two factor authentification.

**Comment by mwarning** [comment]
SSH passphrase support is added in 3.1.1.: https://github.com/mwarning/trigger/commit/1e4985d4dfe7b1f8cd557a6534dbced00b9c3111

**Comment by mwarning** [comment]
I have not tested the feature yet.

**Comment by mwarning** [comment]
I had to undo the passphrase support for now. The problem is that the ssh lib needs the passphrase when loading the key from the database. This causes a lot of issues right now.
