### ISSUE TITLE
Feature request: allow different user names

### ISSUE THREAD

**Issue by basxto** [mwarning/trigger#47]
It would be nice if it would be supported to have different user names for open close.
My hackerspace user names close and open combined with login scripts.

**Comment by mwarning** [comment]
Is this for SSH? And you have different users logins to trigger open and close?

**Comment by basxto** [comment]
Yes, this is through ssh. Both users (open and close) have the pub keys of all members witg door access

**Comment by mwarning** [comment]
I see. Such a feature would need a redesign of the app. I do not see this happening in the near future.

**Comment by basxto** [comment]
Okay, I use two configurations now, which kinda works.

**Comment by mwarning** [comment]
I already had the idea to make it possible to mix https/ssh/... actions. This would enable this feature request as well. But it needs quite some work.
Closing this for now.
