### ISSUE TITLE
"SSID Mismatch" debugging?

### ISSUE THREAD

**Issue by ckuethe** [mwarning/trigger#48]
Could you add an "Expected" vs "Actual" output to the SSID Mismatch notification? I'm pretty sure I'm typing the SSID correctly but am getting a mismatch.

Samsung Galaxy S9+, Android 10, Sept 2020 security patch level. Maybe Samsung did something that breaks SSID lists?

**Comment by mwarning** [comment]
I will do that. Does the SSID contain a ',' by any chance?

**Comment by ckuethe** [comment]
No. Mostly alphanumeric, no whitespace, and a few of the safer symbols like `-`, `_`, or `.`.

**Comment by mwarning** [comment]
Hm, that should be safe.

**Comment by ckuethe** [comment]
The detected SSID is ''.

**Comment by mwarning** [comment]
Can you enable GPS as an experiment?

**Comment by mwarning** [comment]
Any news?

**Comment by ckuethe** [comment]
My SSID is still not detected. I just sent you some logs.

![Screenshot_20201102-203321_Trigger](https://user-images.githubusercontent.com/1131751/97950206-02b37480-1d4b-11eb-8181-ee367fc510d6.jpg)
![Screenshot_20201102-203351_Permission controller](https://user-images.githubusercontent.com/1131751/97950208-034c0b00-1d4b-11eb-913b-defbe4c2a039.jpg)
![Screenshot_20201102-203410_Permission controller](https://user-images.githubusercontent.com/1131751/97950209-03e4a180-1d4b-11eb-9c73-2c0ff49efa87.jpg)

**Comment by mwarning** [comment]
ok, thanks a lot.

Looks like I need to get hold of an Android 10 device and do some debugging.

**Comment by mwarning** [comment]
I got an Android 10 device and it does not work. I will look into it.

**Comment by mwarning** [comment]
Fixed in 3.1.3
