### ISSUE TITLE
Nuki connect support

### ISSUE THREAD

**Issue by emiroztrk** [mwarning/trigger#49]
Hello there,

I installed the trigger app on my android phone and made the necessary settings for nuki, you can see below.

![WhatsApp Image 2021-03-11 at 10 37 19](https://user-images.githubusercontent.com/40431299/110753941-4158be80-8258-11eb-9906-6d84f49ca8cc.jpeg)

But after making these adjustments, I cannot connect to the device and send commands.

My Nuki device was tested in 2 cases
- previously installed on its own app
- and factory reset and tested

Trigger application failed to connect nuki in both cases. Is there something we did wrong?

**Comment by mwarning** [comment]
Thank for testing!
What Android Version do you use?

**Comment by mwarning** [comment]
Maybe asking for the right permissions is not working properly or has changed in newer android versions.

**Comment by mwarning** [comment]
I usually start to pair both devices.

**Comment by L3K0V** [comment]
I have the same issue, the app didn't ask for Bluetooth permissions :(

Any updates on this?

**Comment by mwarning** [comment]
I had Nuki support developed with Android 7.1.x.
What Android version do you use? Did you make sure to enable Bluetooth?

**Comment by mwarning** [comment]
I just tested successfully with Android 10 and "Nuki Smartlock 2.0":

1. Press the door knob button on the Nuki Smartlock for 3 seconds until the ring lights up (pairing mode)
2. Enable Bluetooth on the phone
3. Pair phone and nuki smartlock
3. Start Trigger, add a new door entry with door type "Nuki SmartLock"
4. Enter the name of the paired Nuki smartlock to the "Lock Name/MAC" field (something like "Nuki_1DAB5E34").
5. Enter some user name (does not really matter)
6. Save door setup
7. If the Nuki smartlock is not in pairing mode anymore, just press the the button again.
8. Press the open door button in Trigger. This will cause Trigger to register with the Nuki Smartlock.

Please let me know if that works for you.

**Comment by L3K0V** [comment]
@mwarning I can confirm that using the procedure you mentioned it is working. I saw that you have also updated the README. For me this issue is closed, thanks!

**Comment by mwarning** [comment]
@L3K0V great! Thank you for the reply.
