### ISSUE TITLE
ssh fails to send commands

### ISSUE THREAD

**Issue by StickyDigit** [mwarning/trigger#52]
Using the latest F-Droid build (3.3.0) on Android 11 with an existing config that had worked just fine, and with a similar new config with a fresh key.

When connecting, the server accepts the key, and Trigger shows "Remote end closed connection".

The connection shows the "Unknown Status Image" regardless.

I added some crude debugging to the server end and it seems Trigger is not sending the commands. They are simply start,stop or status.

Test from laptop:
20210602_140440 : invoked with 'stop'
20210602_140440 : UNLOCKED
20210602_140445 : invoked with 'status'
20210602_140445 : UNLOCKED

Test from Trigger
20210602_140557 : invoked with ''
20210602_140557 : Invalid
20210602_140601 : invoked with ''
20210602_140601 : Invalid

in authorized_keys I have lines like:

```
no-port-forwarding,no-x11-forwarding,no-agent-forwarding,command="/home/pi/bin/controldoor" ssh-[keyver] [pubkeydata] [comment]
```
..which worked fine before, and work fine when called from laptop with e.g.
`ssh -i testkey pi@$IP status`

The server command (controldoor) looks like this:

```
#!/bin/bash
arg="$1"
[ -z "$1" ] && arg="$SSH_ORIGINAL_COMMAND"
debug="1"

[ ! -z "$debug" ] && {
    now=$(date +%Y%m%d_%H%M%S)
    logfile=/tmp/motionconlog
    echo "$now : invoked with '$arg'" >> "$logfile"
}

emit(){
    [ ! -z "$debug" ] && echo "$now : $1" >> "$logfile"
    echo "$1"
}

case $arg in
 start) doorlock start && e="LOCKED" || e="LOCKFAIL";;
 stop) doorlock stop && e="UNLOCKED" || e="UNLOCKFAIL" ;;
 status)
        doorlock status >/dev/null 2>&1 &&\
         e="LOCKED" ||\
         e="UNLOCKED"
 ;;
 *) e="Invalid arg" >&2 ;;
esac
emit $e
```
..crude, but it worked previously, and clearly is getting called when Trigger connects, but no command is sent.

**Comment by StickyDigit** [comment]
Just set up another one on a fresh device (also android 11). I notice it connects four times with no args at startup.
To reproduce. Force stop. Re-open. After a brief delay, four connections happen.
I'll test now with a 10 and a 7.

**Comment by mwarning** [comment]
Sorry for the breakage. The latest release was a bit heavy. Thank your for all the data, I will look into it later.

**Comment by StickyDigit** [comment]
Thanks for caring :)

7's a fail too :( I'll not bother with 10 unless you ask me to. As 11 and 7 are affected I'd guess it's the same for all.

FWIW, the existing config I used was an RSA key from a much earlier version. All my new tests including the successful one from a latptop were using ed25519.

**Comment by mwarning** [comment]
Ok, so it works with trigger 3.3.0 if you generate a new key (ed25519 and RSA)?
But if you had the RSA key from trigger before 3.3.0, update trigger to 3.3.0, then it does not work anymore?

**Comment by StickyDigit** [comment]
Fails every way I've tried.

**Comment by StickyDigit** [comment]
Laptop booted :)
Reading back I can see why you'd ask. No. 3.3.0 fails to send commands with the old existing config (RSA), and with a new config (ed25519), as well as completely new config on different devices that did not have Trigger already installed,, both android 11 and 7. It connects just fine, and kicks off the command, but does not pass the argument specified in the configuration any more.

**Comment by StickyDigit** [comment]
So to be sure:
From laptop, with debug set on server script as above.

```
ssh -i ./id_ed25519 pi@192.168.2.105 status
```
At server we see.
```
20210602_174328 : invoked with 'status'
20210602_174328 : UNLOCKED
```
From Trigger, with unlock set to 'stop', lock set to 'start' and status set to 'status'. When first launching Trigger we see this at the server.
```
20210602_174631 : invoked with ''
20210602_174631 : Invalid
20210602_174632 : invoked with ''
20210602_174632 : Invalid
20210602_174632 : invoked with ''
20210602_174632 : Invalid
20210602_174632 : invoked with ''
20210602_174632 : Invalid
```
Hitting Unlock button we get this at the server. Same happens with lock.
```
20210602_174740 : invoked with ''
20210602_174740 : Invalid
```
Lock does the same. Dropping the WiFi , Trigger shows disconnected instead of Unknown Status. Clearly as Trigger is not sending 'status' command, it never shows anything but Unknown Status or Disconnected.

**Comment by StickyDigit** [comment]
Created a new RSA config. Still connecting just fine, and still sending no commands.

With eyes on the number of connections at startup, when starting from FC it still does four connections as the first config, but when switching to the new config (when already running) it only connects once. Flipping between configs it continues to probe for status only once. Seems the "four connects" only happens at startup.

Happy to help if you want me to try anything.

**Comment by mwarning** [comment]
What open command did you use?
I tested Trigger 3.2.2 and 3.3.0 with SSH and could not get `command="/home/pi/bin/controldoor"` in `.ssh/authorized_keys` to receive any arguments.

Could you try to remove the command from `.ssh/authorized_keys` and use `/home/pi/bin/controldoor start` as Open Command setting in trigger. That was working for me. The arguments were also passed.

I also tested creating a RSA key (2048) in Trigger 3.2.2 and then updated to Trigger 3.3.0. The key way still working find.

**Comment by StickyDigit** [comment]
I could... I'll try it... but it always used to work and should work with the command nailed down in the keys and the args only being passed. Much more secure. I've used it a lot as shown, and it's only recently broken.
Will report back in a few minutes.

**Comment by StickyDigit** [comment]
FWIW.. it clearly works in the keys when invoked from a laptop as I've detailed above.

**Comment by StickyDigit** [comment]
Yup.. with no command nailed down it works, but of course then anything with that key can now run any command.

With an identical setup as I'd done previously for trigger, for a key on my laptop I can run ssh -i ./id_ed25519 pi@$IP status and it executes the command in the authorized_keys with the argument 'status' passed as SSH_ORIGINAL_COMMAND to the env of the command.

If I run it from the laptop with '-t' to force a tty to be allocated I get 'UNLOCKED' as I do without the -t, and also Connection Closed. Are you getting connectbot to use a tty when it need not? I still get the response on my laptop, and the arg is passed to the server, however that may not be so for connectbot.

I'll have a go with connectbot and see how it behaves for this case.

**Comment by StickyDigit** [comment]
Oddly.. I can't make it work with connectbot. I set simply 'status' as the automation, with or without carriage return, and it's not passed as it was with ssh from the laptop, or the previous incarnation of Trigger. 
The command does get invoked, but is not passed SSH_ORIGINAL_COMMAND. It's as if its not being called like normal ssh command such as "ssh name@host command", but rather "ssh name@host.. then once connected and given a terminal... command"
Unfortunate.

**Comment by StickyDigit** [comment]
Attempted to downgrade to 3.2.1. As soon as I made a config it FC'd itself on LineageOS 18.1.

3.2.2 works as expected. Simply using 'status' as the command gets passed through as SSH_ORIGINAL_COMMAND

Of course, on android 11 I cannot choose ext SD to select the images for the config, but it's certain that something has changed in the switch to connectbot which breaks passing commands to ssh in the 'normal' way.

**Comment by mwarning** [comment]
ok, I think I have fixed the issue. See https://github.com/mwarning/trigger/commit/f628211a5fbb0601735c4f71b0cc1dfa209f7f49

**Comment by mwarning** [comment]
Are you able to build and test this change?

**Comment by StickyDigit** [comment]
Wilco. In about half an hour.

**Comment by StickyDigit** [comment]
Yes. It still runs status four times at startup, but it works. Nice one!

20210606_183359 : invoked with 'status'
20210606_183359 : invoked with 'status'
20210606_183359 : UNLOCKED
20210606_183400 : invoked with 'status'
20210606_183359 : UNLOCKED
20210606_183400 : invoked with 'status'
20210606_183400 : UNLOCKED
20210606_183400 : UNLOCKED

**Comment by mwarning** [comment]
No idea why status runs four time at first. I does not for me. But let's close this ticket.

**Comment by StickyDigit** [comment]
Added nanoseconds to logging so you can see that it's actually four individual logins at startup. They tripped over each other a bit in the scramble to commit to log.

20210606_184057.711496169 : invoked with 'status'
20210606_184057.768716948 : invoked with 'status'
20210606_184057.711496169 : UNLOCKED
20210606_184057.978228139 : invoked with 'status'
20210606_184057.768716948 : UNLOCKED
20210606_184057.978228139 : UNLOCKED
20210606_184058.301295892 : invoked with 'status'
20210606_184058.301295892 : UNLOCKED

**Comment by mwarning** [comment]
I seems to be only once for me. Need to check another time...

**Comment by mwarning** [comment]
Nvm., I was checking the wrong command.
