### ISSUE TITLE
Reply pattern is not available when MQTT is chosen

### ISSUE THREAD

**Issue by blaxer** [mwarning/trigger#55]
First of all thank you for the great app! Just one little problem I am having with v3.3.1 (obtained from F-droid if that matters)

The document mentions that the reply patterns should be available, but when I select generic MQTT those options disappear.

TIA!

**Comment by mwarning** [comment]
hi, thank you for testing!
I did not put any call into Trigger to read any text via MQTT. It might be easy, but then I would need to test it and I do not know when I will have and motivation to do so. Feel free to provide a merge request to call the right methods here (https://github.com/mwarning/trigger/blob/master/app/src/main/java/app/trigger/mqtt/MqttRequestHandler.java#L129) - even if it just outputs the text to console, I would do the rest.

**Comment by mwarning** [comment]
@blaxer never mind. I was wrong. :)
MqttRequestHandler.java contains a callback to read responses. I have added the UI elements for the match pattern configuration.

**Comment by mwarning** [comment]
https://github.com/mwarning/trigger/commit/e69594f52f8054dd50c9a147c3856ab9daafaef0
