### ISSUE TITLE
backup import problems from cloud storage

### ISSUE THREAD

**Issue by flashfingaz** [mwarning/trigger#60]
I tried to import my backup from my nextcloud folder which gave me
`java.io.FileNotFoundException: Error downloading file: backup.json`

so I tried to save the file to another folder where I cannot choose it (greyed out).
when I export some bogus settings to that folder, the file could be chosen.
if i change the name of my backup file to 'trigger-backup.json' as the app suggests when exporting nothing changes
what I also noticed is that the exported file gets an icon and my backup file does not.

things got even weirder. if i export my bogus door data into a backup and place it into the download folder of my android and then rename a copy of my backup to match with that file and copy it over to the download folder - i can open it. but then the import fails with random problems where random parts of the key/value pairs are reported to not be a string. I played around with this a bit and removed keys that where empty as I thought maybe the ssh keys make the backup json to big to parse. and indeed with every change that i did the error was in another (seemingly random) part of the file.

after all, this might be two independent problems and at least the first one (picking the correct file) might be more of an local issue that i was not able to figure out yet. but maybe there is actually a bug with things... :) will add more evidence later if needed. can even provide the full backup file as i will create a new key and disable the old one within the next days

**Comment by mwarning** [comment]
I have heard about such a problem. What Android version do you use, and how big is the export? Do you have pictures in the setup?

**Comment by mwarning** [comment]
Do you have some concrete steps on how to reproduce the problem?

**Comment by flashfingaz** [comment]
ah sorry, i kept forgetting about my plan to upload stuff. i'll screenshot my way through and upload it here (including the backup file i tried to import as the key is now retired anyway. brb! :)

**Comment by flashfingaz** [comment]
![Screenshot_20210803-134250](https://user-images.githubusercontent.com/8404416/128009728-e8ed9b40-c044-4340-8434-5ee5072b02da.png)
this is the error i get when trying to import the backup file from nextcloud which makes some sort of sense (but then not as the file is already synced to the androids filesystem manually via nextcloud client)

**Comment by flashfingaz** [comment]
![Screenshot_20210803-133646](https://user-images.githubusercontent.com/8404416/128009923-cbbb6d1d-6bfb-40b2-bba4-66877e059f95.png)
this is the problem where i'm not able to choose the json. 
interesting situation: assume this file is a and there is also another file b (which is an fresh export of some bogus trigger data). the icon of file a will be as in the screenshot, whereas the icon of file b will be brackets (guess thats the icon for json files...). so it seems the system is not able to distinguish by the file extension which is all weird by itself. but gets better: when i rename file a to file b, the resulting file can be chosen although nothing changed....

**Comment by flashfingaz** [comment]
![Screenshot_20210803-133629](https://user-images.githubusercontent.com/8404416/128010470-24956438-af46-4bf2-b48d-caddec907f5f.png)
![Screenshot_20210722-184107](https://user-images.githubusercontent.com/8404416/128010474-4eb9f24f-d635-41f6-baa4-43024a90119e.png)
finally these are the errors i get when i do like described above and import the file. i also checked the content of the json, used a json syntax checker and looked for obvious errors in the file

**Comment by flashfingaz** [comment]
[backup_json.txt](https://github.com/mwarning/trigger/files/6923805/backup_json.txt)
this is the backup file (had to rename it as github won't accept with original extension)
there is nothing sensitive in there, the process how to open the door is no secret and the key was only used to unlock the door and is already replaced.

details also here: https://wiki.un-hack-bar.de/index.php/Projekt:T%C3%BCrsteuerung#via_app

**Comment by flashfingaz** [comment]
phone is a CAT S61 running stock Android 9

**Comment by mwarning** [comment]
Thank you for the information. I will take a look.

**Comment by mwarning** [comment]
ok, the JSONException appears, because your json file contains the SSH keypair value in the old `keypair` format.
In Trigger 3.2.3 `keypair` contains just the private ssh key. But in Trigger 3.3.0 it is a json element as string.

I have fixed that in https://github.com/mwarning/trigger/commit/e8e02a5c16738b5c3eb88bdc3c5c15bb8edd5410

**Comment by mwarning** [comment]
@flashfingaz are you able to build Trigger yourself and test the change?

As for the file selection issue, I cannot reproduce it, but I also have not could storage to experiment with.
But I think this is a security issue. Can you try to move the json file (that you cannot open) to a different location (Download folder should be good) and see if you still cannot open/select the file?

**Comment by mwarning** [comment]
The 3.3.3 release contains the fix for the exception. As for the cloud storage, I have no setup to test it.

**Comment by mwarning** [comment]
there is nothing i can test right now. i will close this for now.
