### ISSUE TITLE
HTTPS peer authentication issue.

### ISSUE THREAD

**Issue by zelch** [mwarning/trigger#61]
When I setup trigger with a basic HTTPS URL for open/close, I get:

javax.net.ssl.SSLPeerUnverifiedException:
Hostname: >my hostname< not verified: ...

Except, the certificate is valid, Chrome on the same device has no problem going to a URL on the same host, the CN matches, the Alt DNS list has the host name as well.

If I disable the hostname check, stuff works, but I can't see any reason why this should be necessary.

**Comment by mwarning** [comment]
Chrome might come with its own root certificates. Did you create that certificate on your own?

**Comment by zelch** [comment]
Nope, it's a fairly standard Let's Encrypt certificate.

**Comment by mwarning** [comment]
I was able to verifiy the problem. Fixed in https://github.com/mwarning/trigger/commit/713cfe5a2311ca4ea2b35c7d7898e00227e2cb14
