### ISSUE TITLE
No documentation on JSON format.

### ISSUE THREAD

**Issue by zelch** [mwarning/trigger#62]
I was hoping to save myself some effort and write out the configuration in JSON, convert to a QR code, and scan it.

Unfortunately, I'm stuck with a very vague 'Invalid QR Code' error, looking at the source this means that something threw JSONException, but the log doesn't include the error message.

I was eventually able to figure it out by exporting as a QR code, scanning with my computer, and reading the JSON...  But it would be nice if there was documentation or examples. :)

**Comment by mwarning** [comment]
I agree. Some documentation would be nice. :)

**Comment by mwarning** [comment]
But JSON format is not really meant to be used except by developers.

The QR-Code is allowed to just be a single link (https://.., ssh://...). This is documented here:
https://github.com/mwarning/trigger/blob/master/docs/documentation.md

**Comment by mwarning** [comment]
Let me close this one, since it is developer documentation that is missing and I do not really have enough time for that. - Sorry :)
