### ISSUE TITLE
Basic auth throwing illegal argument exception

### ISSUE THREAD

**Issue by daniel-j-h** [mwarning/trigger#67]
Hey folks, I got around trying out the latest release with basic auth, but it seems like I'm running into an exception.

Here is an example how my command url looks like (I'm using this on my laptop)

```bash
http://c18z907f-f9cc-44d5-9dca-11ee5dc4e396:fddc2458-af53-4621-b89e-dfa02bf79410@192.168.1.115/relay/0?turn=on&timer=300
```

and here is a screenshot of the exception

![Screenshot_20211105-111446](https://user-images.githubusercontent.com/527241/140512271-00192348-9628-43e5-a347-f56334b78690.jpg)

which seems to come from here https://github.com/mwarning/trigger/blob/e5ed285b296a1af8a223103a5187bb2f2e32ed63/app/src/main/java/app/trigger/https/HttpsRequestHandler.java#L110

Let me know if I can provide you folks with more information.

Related
- https://github.com/mwarning/trigger/issues/66
- https://github.com/mwarning/trigger/pull/63

**Comment by mwarning** [comment]
Base64.DEFAULT seems to append a newline (NL+CR) to be appended.
Fixed in https://github.com/mwarning/trigger/commit/3a4d792ad66d6a8eabf63e6ac9d0a95840023b19
