### ISSUE TITLE
HTTPS Client Certificates for authentication

### ISSUE THREAD

**Issue by cuechan** [mwarning/trigger#68]
Hi, we are using Client TLS Certificates for authentication for doorlocks at our hackspace . Unfortunately i was not able to import my certificate into the app. While importing the certificate it shows `Done, Read primary:key` but when opening the door it fails with `400 No required SSL certificate was sent`.

How can i use a TLS Client certificate for authentification?

**Comment by mwarning** [comment]
The easiest would be to initally fetch the certifiacte from the door. Under "Manage TLS Certificate" you can add a "Certificate URL" (e.g. "https://our-door.net"). This way you can import the certifcate. Then, if you want, you can then export it with the export button.

**Comment by mwarning** [comment]
Maybe there is a bug that is triggered with your approach, of course.
Feel free to send me testing certificates so I can try to recreate the problem on my side.

**Comment by mwarning** [comment]
More code for TLS support was added. But it was not tested yet. Let's hope that it will this issue.

**Comment by mwarning** [comment]
So far Trigger did not support client certificates. Now it does, but so far it is not released and untested.
