### ISSUE TITLE
Wishlist: Geofence

### ISSUE THREAD

**Issue by rdorsch** [mwarning/trigger#72]
Hi,

many thanks for the trigger app, which is one of my most used apps.

There are two items which I am currently still missing:
- passphrase support (see issue #45) or any other option to secure the access to the ssh-key (e.g. fingerprint reader)
- geofence: I opened once the wrong door accidentally and could not close it, since I was far away from that door. Thus it would be a great feature if a geofence could be defined and if I accidentally want to open a non-local door, e.g. a warning with a confirmation or cancel option should pop-up.

There is a tutorial on geofencing available:
https://developer.android.com/training/location/geofencing

A simpler option could be to check if the device is in a certain wifi network and if not fire a warning. I assume for this most of the code is already in trigger.

**Comment by mwarning** [comment]
Nice to hear that this app helps. :-)

> A simpler option could be to check if the device is in a certain wifi network and if not fire a warning. I assume for this most of the code is already in trigger.

That particular feature is already there (`SSIDs`). Enter one or more SSIDs (separated by commas) and you will only be able to send command if connected to one of those WiFi networks.

As for your two listed features, I understand that they would be nice to have, but currently I do not have the motivation to implement it. If someone wants to create a merge request, then I will be happy to merge it (if I am able to maintain the code).

**Comment by rdorsch** [comment]
If I understand it correctly, if I want to open the door w/o being in the wifi, I would need to go into settings, disable the SSID check, open the door, go back to settings and enable the SSID check again. Here a shortcut with a confirmation option if the not in the wifi network (yes I want to open it) would be quite useful.

**Comment by mwarning** [comment]
> If I understand it correctly, if I want to open the door w/o being in the wifi, I would need to go into settings, disable the SSID check, open the door, go back to settings and enable the SSID check again.

Correct.

I wonder if a shortcut is something that is need by many people. Well, I am uncertain about this.

**Comment by StickyDigit** [comment]
Just a thought...
Perhaps an additional item like 'when SSID "x" visible' could serve well for 'any-net but not anywhere' situations.


On 11 March 2022 23:09:54 GMT, Moritz Warning ***@***.***> wrote:
>> If I understand it correctly, if I want to open the door w/o being in the wifi, I would need to go into settings, disable the SSID check, open the door, go back to settings and enable the SSID check again.
>
>Correct.
>
>I wonder if a shortcut is something that is need by many people. Well, I am uncertain about this.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/mwarning/trigger/issues/72#issuecomment-1065622584
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
-- 
Sent from a phone. Please excuse my brevity.

**Comment by rdorsch** [comment]
I used as workaround to connect to the NATed IPv4 address in the wifi network instead of the IPv6 address. But whenever the phone is not in the Wifi network yet, it does not work. Usually that happens when I am in a hurry.

Instead of changing the trigger settings, I usually trigger a wifi scan.

If I could just hit a confirm button for yes that is ok in these cases, that would help.

**Comment by mwarning** [comment]
I have added a dialog to temporarly disable the WiFi check (wifi status and wifi ssid check). Let's see if that works.

**Comment by mwarning** [comment]
I added ssh passphrase supoort. But it is not working yet.

**Comment by mwarning** [comment]
This approach only stores is temporarely (until the app exits or the another door profile is selected). So you need to reenter the passphrase.

**Comment by rdorsch** [comment]
Why do you invalidate the passphrase if another door profile is selected? At least in my case, I use the same private key for all doors. So I would rather never need to invalidate it (except if the app exits, then it is certainly gone). Is it possible to invalidate clear the passphrase cache only if the new door profile uses a different passphrase?

**Comment by mwarning** [comment]
That should be possible. I will do that.

**Comment by mwarning** [comment]
I have added the features. But there might be bugs, of course.
Let's close this issue and create new ones for those bugs.
