### ISSUE TITLE
Is this app still in the Play Store?

### ISSUE THREAD

**Issue by s3lph** [mwarning/trigger#80]
Hi

When clicking on the "Get it on Google Play" link in the Readme, I get presented with the following error message:
![We're sorry, the requested URL was not found on this server. - Google Play](https://github.com/mwarning/trigger/assets/5564491/55f08ef9-b34b-4f69-ad4b-29f9ff870329)

Is this app still available on the Play Store? If so, could you fix the link?
Thanks!

**Comment by mwarning** [comment]
Ah yes. Google deaktivated my user account two ago  because I was not using it or they required some new identification stuff...

**Comment by s3lph** [comment]
@mwarning thanks for the reply.

What will that mean for users, though? Are you planning to re-publish it on Google Play, or will it stay off indefinitely?

**Comment by mwarning** [comment]
I will re-register at some point. The App is also available via f-droid.

**Comment by mwarning** [comment]
But anyone can put it on gplay. As long it is non-commercial (according to the license)
